version: '2'

services:
  db:
    container_name: docker_project-db
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --sql-mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    volumes:
      - ./mysql/:/var/lib/mysql
      - ./tmp/:/var/tmp
      - /etc/localtime:/etc/localtime:ro
    environment:
      MYSQL_ROOT_PASSWORD: docker_project_root_password
      MYSQL_DATABASE: docker_project_db
      MYSQL_USER: docker_project_user
      MYSQL_PASSWORD: docker_project_password
    networks:
      docker_projectnet:
        ipv4_address: 172.32.0.11

  web:
    container_name: docker_project-web
    build: ./web
    depends_on:
      - db
    volumes:
      - ../app:/var/app
      - ./tmp/:/var/tmp
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "80:80"
    networks:
      docker_projectnet:
        ipv4_address: 172.32.0.12
    extra_hosts:
      - "ide.local: 172.32.0.1"

networks:
  docker_projectnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.32.0.0/24
